version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0

vars:
  IS_CI:
    sh: 'test -n "$CI" && echo "true" || echo "false"'

jobs:
  validate_modules:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - terraform/install
      - run:
          name: "Install Task"
          command: |
            sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - run:
          name: "Validate changed modules"
          # This command will first determine if there are changes.
          # If the CHANGED_MODULES variable is empty, the `if` condition will be false
          # and the job will succeed without running the validation task.
          command: |
            CHANGED_MODULES=$(git diff-tree --no-commit-id --name-only -r "$CIRCLE_SHA1" | awk -F'/' '/^modules\// {print $2}' | sort -u | tr '\n' ' ')
            if [ -n "$CHANGED_MODULES" ]; then
              echo "Changes detected in modules: $CHANGED_MODULES"
              task validate-changed
            else
              echo "No changes detected in any modules. Skipping validation."
            fi
  
  check_formatting:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - terraform/install
      - run:
          name: "Check Terraform formatting"
          command: terraform fmt -check -recursive
          
  update_documentation:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys # This step is crucial for allowing git push
      - terraform/install
      - run:
          name: "Install terraform-docs"
          command: |
            curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
            tar -xzf terraform-docs.tar.gz
            sudo mv terraform-docs /usr/local/bin/
      - run:
          name: "Install Task"
          command: |
            sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - run:
          name: "Generate documentation"
          command: task docs
      - run:
          name: "Commit and push documentation changes"
          command: |
            # Check if there are any changes to commit
            if ! git diff --quiet --exit-code; then
              echo "Documentation changes detected. Committing and pushing..."
              # Configure git
              git config user.email "ci-bot@circleci.com"
              git config user.name "CI Bot"
              
              # Add, commit, and push the changes
              git add .
              git commit -m "docs: auto-generate and commit documentation"
              git push origin HEAD
            else
              echo "Documentation is already up-to-date."
            fi

workflows:
  quality_gate:
    jobs:
      - validate_modules
      - check_formatting
      - update_documentation:
          requires:
            - validate_modules
            - check_formatting