version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0

jobs:
  validate_modules:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - terraform/install
      - run:
          name: "Install Task"
          command: |
            sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - run:
          name: "Validate changed modules"
          command: task validate-changed
  
  check_formatting:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - terraform/install
      - run:
          name: "Check Terraform formatting"
          command: terraform fmt -check -recursive
          
  check_documentation:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # This step installs the terraform CLI itself
      - terraform/install
      # This step downloads and installs the terraform-docs binary
      - run:
          name: "Install terraform-docs"
          command: |
            curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
            tar -xzf terraform-docs.tar.gz
            sudo mv terraform-docs /usr/local/bin/
      - run:
          name: "Install Task"
          command: |
            sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - run:
          name: "Check if documentation is up-to-date"
          command: task check-docs

workflows:
  quality_gate:
    jobs:
      - validate_modules
      - check_formatting
      - check_documentation